name: Run Bruno Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bruno-test:
    name: Execute Bruno CLI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from the repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run Bruno Tests
        run: bru run Reqres --reporter-html HTMLReporter/Results.html

      - name: Upload Test Report in artifact location
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Bruno HTML Test Result
          path: HTMLReporter/Results.html
